// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf8RsevfE2-Hv4BBHJ--WyxwgYAp2AnNI',
    appId: '1:736554910585:web:fce66c3ada90d50feba5a8',
    messagingSenderId: '736554910585',
    projectId: 'recruitswift',
    authDomain: 'recruitswift.firebaseapp.com',
    storageBucket: 'recruitswift.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkA_2QpQ89lr4WsHJfN0qHeE-5NfgSC9I',
    appId: '1:736554910585:android:b9ee47c19d8d750feba5a8',
    messagingSenderId: '736554910585',
    projectId: 'recruitswift',
    storageBucket: 'recruitswift.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCf8RsevfE2-Hv4BBHJ--WyxwgYAp2AnNI',
    appId: '1:736554910585:web:754eb63dd19312a7eba5a8',
    messagingSenderId: '736554910585',
    projectId: 'recruitswift',
    authDomain: 'recruitswift.firebaseapp.com',
    storageBucket: 'recruitswift.firebasestorage.app',
  );
}
